name: Generate and Push WScript API Documentation

on:
  workflow_dispatch: 

jobs:
  doxygen-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen
        
      - name: Run Doxygen
        run: doxygen Doxyfile_scripting

      - name: Generate  markdown
        run: |
          mkdir -p out
          python tools/doxygen_xml_to_md.py docs/xml out/wolvenkit.md

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.WSCRIPT_DOC_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Clone WolvenKit Wiki Repo
        run: |
          git clone git@github.com:notaspirit/WolvenKit-8-Wiki.git

      - name: Validate API Docs File
        run: |
          cd WolvenKit-8-Wiki/wolvenkit-app/wscript
          grep -Fq "<!-- AUTOGEN_MARKER_START -->" api-documentation.md
    
      - name: Update WScript API Docs
        run: |
          cd WolvenKit-8-Wiki/wolvenkit-app/wscript
          awk '
          /<!-- AUTOGEN_MARKER_START -->/ {
            print
            system("cat ../../../out/wolvenkit.md")
            exit
          }
          { print }
          ' api-documentation.md > api-documentation.new.md
          mv api-documentation.new.md api-documentation.md
          
      - name: Commit and push
        run: |
          cd WolvenKit-8-Wiki
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Automated WScript API Update"
          git push
