name: Generate Doxygen JSON

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  doxygen-json:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Install Doxygen
      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen

      # 3️⃣ Run Doxygen
      - name: Run Doxygen
        run: doxygen Doxyfile_scripting

      # 4️⃣ Upload JSON artifact
      - name: Upload XML
        uses: actions/upload-artifact@v4
        with:
          name: doxygen-xml
          path: docs/xml/

      - name: Generate TS definitions
        run: |
          mkdir -p out
          python tools/doxygen_xml_to_ts.py docs/xml out/wolvenkit.d.ts
      
      - name: Upload TS artifact
        uses: actions/upload-artifact@v4
        with:
          name: wolvenkit-ts-defs
          path: out/*.d.ts

      - name: Generate  markdown
        run: |
          mkdir -p out
          python tools/doxygen_xml_to_md.py docs/xml out/wolvenkit.md
                
      - name: Upload md artifact
        uses: actions/upload-artifact@v4
        with:
          name: wolvenkit-md
          path: out/*.md
